### ISSUE TITLE
compile error: [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined

### ISSUE THREAD

**Issue by naderi4** [unhurried/bookmark-with-image#2]
hello
thank you for share your project
I have got an **compile time error** 

```
D:\bookmark-with-image-2.1.1>npm run electron:serve

> bookmark-with-image@2.1.1 electron:serve D:\bookmark-with-image-2.1.1
> vue-cli-service electron:serve

 INFO  Starting development server...
Starting type checking service...
Using 1 worker with 2048MB memory limit
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                               4:06:24 PM

 error  in ./src/main.ts

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in D:\bookmark-with-image-2.1.1\node_modules\@babel\helper-compilation-targetspackage.json
    at applyExports (internal/modules/cjs/loader.js:506:9)
    at resolveExports (internal/modules/cjs/loader.js:522:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1052:27)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\bookmark-with-image-2.1.1\node_modules\@babel\preset-env\lib\debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (D:\bookmark-with-image-2.1.1\node_modules\@babel\preset-env\lib\index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)

 @ multi (webpack)-dev-server/client?http://localhost:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

Type checking in progress...
No type errors found
Version: typescript 3.5.3
Time: 8784ms
```

**Comment by naderi4** [comment]
i updated plugins and problem solved
thank you
